#   Configure file for pyWeather.py 
#   (c) 2025 Kevin Scott   Written Tuesday 20 January 2026  16:18:35
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.38"
myNAME = "pyWeather"

[DATA]
month = 1
year = 2026
startDate = "02-07-2023"
endDate = "19-01-2026"
noOfLines = [ 908, 729, 179,]
locations = [ "All", "Hedon", "Gilberdyke",]
endGilberdyke = "15-07-2025"
startHedon = "17-07-2025"
location = "Hedon"

[GRAPH]
width = 1400
height = 1000
X_pos = 40
Y_pos = 40
lineWidth = 1
lineStyle = "-"
lineColour = "blue"
alpha = 0.75
grid = true
